image: golang:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - go test .

compile:
  stage: build
  script:
    - mkdir -p build
    - go build -o build/ .  # Linux build
    - GOOS=windows GOARCH=amd64 go build -o build/ . # Windows x86 build
    #- CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -o build/ . # Mac OS X pre-arm64
  artifacts:
    paths:
      - build
