# https://github.com/actions/create-release

name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
    - name: Build
      run: make build
      #run: go build -v ./...
    - name: Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        # Can use body_path: ... to load contents of a file instead.
        body: |
          Release triggered by Github Workflow release.yml file.
        draft: false
        prerelease: false
